import { Barlow } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar/Navbar";

const fontStyle = Barlow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fontStyle.className}>
        <Navbar>{children}</Navbar>
      </body>
    </html>
  );
}
