import { Barlow } from "next/font/google";
import "./globals.css";
import connectMongodb from "@/services/ConnectMongoose";

const fontStyle = Barlow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectMongodb();

  return (
    <html lang="en">
      <body className={fontStyle.className}>{children}</body>
    </html>
  );
}
